
import  {ShopContextProvider}  from "@/context/ShopContext";
import './globals.css';

export const metadata = {
  title: 'E-COMMERCE PRODUCT PAGE || PRINCESS JEWEL JEL-EDEMA',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ShopContextProvider>{children}</ShopContextProvider></body>
    </html>
  )
}
